---
- hosts: all
  tasks:
  - name: Create security group that allows SSH
    azure_rm_securitygroup:
     resource_group: ansibletrainingrg
     name: secgroup001
     rules:
       - name: SSH
         protocol: Tcp
         destination_port_range: 22
         access: Allow
         priority: 101
         direction: Inbound
