---
- hosts: all
  tasks:
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: changemerg
      name: testvn001
      address_prefixes: "10.10.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
     resource_group: changemerg
     name: subnet001
     address_prefix: "10.10.0.0/24"
     virtual_network: testvn001
