---
- hosts: all
  tasks:
  - name: restart everything
    command: echo "this task will restart the web services"
    notify: "restart web services"
    
  handlers:
  - name: restart apache
    service: name=httpd state=restarted
    listen: "restart web services"

