---
- hosts: all
  tasks:
   - name: Install Nginx
     yum:
      name=nginx
      state=installed
      update_cache=true
     notify:
      - Start Nginx

  handlers:
   - name: Start Nginx
     service:
      name=nginx
      state=started
